micronaut:
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
            - POST
            - GET
            - DELETE
  application:
    name: "accounts"
    api:
      version: v1
    hollow:
      account:
        path: /tmp/hollow/dev/account
        version: v1
        numStatesBetweenSnapshots: 1
  router:
    static-resources:
      default:
        paths: classpath:static
        mapping: /**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**