apiVersion: v1
kind: ConfigMap
metadata:
  name: osaccounts-api-configmap
  namespace: os-dev
  labels:
    app: osaccounts-api
    chart: osaccounts-api-latest
    heritage: Tiller
    release: accounts-release
    version: latest
data:
  osaccounts-api-configmap-key: |
    micronaut:
      application:
        api:
          version: v1
        hollow:
          account:
            path: /tmp/hollow/prod/account
            version: v1