apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-configmap"
  namespace: "os-{{ .Values.env }}"
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Values.deployment.image.tag }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    version: {{ .Values.deployment.image.tag | quote }}
data:
  {{ .Chart.Name }}-configmap-key: |
    hollow:
      bucket: "{{ .Values.configmap.properties.hollow.bucket }}"
      domain: "{{ .Values.configmap.properties.hollow.domain }}"
      namespace: "{{ .Values.configmap.properties.hollow.namespace }}"
      applicationName: "{{ .Values.configmap.properties.hollow.applicationName }}"