apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-configmap"
  namespace: "os-{{ .Values.env }}"
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Values.deployment.image.tag }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    version: {{ .Values.deployment.image.tag | quote }}
data:
  {{ .Chart.Name }}-configmap-key: |
    micronaut:
      application:
        api:
          version: "{{ .Values.configmap.properties.api.version }}"
        hollow:
          account:
            path: "{{ .Values.configmap.properties.hollow.account.path }}"
            version: "{{ .Values.configmap.properties.hollow.account.version }}"
            numStatesBetweenSnapshots: "{{ .Values.configmap.properties.hollow.account.numStatesBetweenSnapshots }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-static-configmap"
  namespace: "os-{{ .Values.env }}"
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Values.deployment.image.tag }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    version: {{ .Values.deployment.image.tag | quote }}
data:
  {{ .Chart.Name }}-css-key: |
    thead {
      font-size: 36px;
      font-family: "Helvetica Neue", serif;
    }
  {{ .Chart.Name }}-index-key: |
    <html><b>HELLO WORLD</b></html>
