apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: "os-{{ .Values.env }}"
  labels:
    name: "{{ .Chart.Name }}-service"
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Values.deployment.image.tag }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    version: {{ .Values.deployment.image.tag | quote }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Chart.Name }}
