env: dev
deployment:
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 1
configmap:
  properties:
    api:
      version: 'v1'
    hollow:
      account:
        path: '/tmp/hollow/dev/account'
        version: 'v1'
        numStatesBetweenSnapshots: 1
ingress:
  host: us-central1-dev.gcp.cloud.os.internal