env: dev
deployment:
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 1
configmap:
  properties:
    hollow:
      bucket: 'os-account-data'
      domain: 'hollow-dev/accounts'
      namespace: 'v1'
      applicationName: 'accounts-1.0'

ingress:
  host: us-central1-dev.gcp.cloud.os.internal