env: stage
deployment:
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 2
configmap:
  properties:
    api:
      version: 'v1'
    hollow:
      account:
        path: '/tmp/hollow/dev/account'
        version: 'v1'
        numStatesBetweenSnapshots: 1
ingress:
  host: us-central1-prod.gcp.cloud.os.internal